language: node_js
node_js: 
  - "stable"
services:
  - mongodb
install:
  - npm install
script:
  - npm test
deploy:
  provider: azure_web_apps
  verbose: true
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: $AZURE_WA_SITE