version: '3'
services:
  meteoapp:
    environment:
      - NODE_ENV=docker
    build: .
    ports: 
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo:4.2.1